import http.server
import socketserver
import json
import subprocess
import os

PORT = 8000
DIRECTORY = os.path.dirname(os.path.abspath(__file__))

class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=DIRECTORY, **kwargs)

    def do_POST(self):
        if self.path == '/api/build':
            content_length = int(self.headers['Content-Length'])
            post_data = self.rfile.read(content_length)
            
            try:
                config = json.loads(post_data.decode('utf-8'))
                self.handle_build(config)
            except Exception as e:
                self.send_error(500, f"Error processing build: {str(e)}")
        else:
            self.send_error(404, "Endpoint not found")

    def handle_build(self, config):
        fw_dir = os.path.join(DIRECTORY, 'firmware')
        config_file = os.path.join(fw_dir, 'custom_config.h')
        
        try:
            with open(config_file, 'w', encoding='utf-8') as f:
                f.write('// Auto-generated by build_server.py\n')
                f.write('#ifndef CUSTOM_CONFIG_H\n')
                f.write('#define CUSTOM_CONFIG_H\n\n')
                f.write(f'#define CUSTOM_MATRIX_ROWS {config.get("rows", 4)}\n')
                f.write(f'#define CUSTOM_MATRIX_COLS {config.get("cols", 6)}\n')
                
                # Check for empty pin
                def clean_pin(p):
                    return p if p else "0"
                
                wiring = config.get('wiring', 'matrix')
                if wiring == 'direct':
                    f.write('#define CUSTOM_DIRECT_PIN_MODE\n\n')
                    direct_pins = config.get('col_pins', [])
                    dp_pins_str = ", ".join([clean_pin(p) for p in direct_pins])
                    f.write(f'#define CUSTOM_COL_PINS {{ {dp_pins_str} }}\n\n')
                else:
                    row_pins = config.get('row_pins', ['PC0', 'PC1', 'PC2', 'PC3'])
                    col_pins = config.get('col_pins', ['PC4', 'PC5', 'PC6', 'PC7', 'PD0', 'PD2'])
                    row_pins_str = ", ".join([clean_pin(p) for p in row_pins])
                    col_pins_str = ", ".join([clean_pin(p) for p in col_pins])
                    f.write(f'#define CUSTOM_ROW_PINS {{ {row_pins_str} }}\n')
                    f.write(f'#define CUSTOM_COL_PINS {{ {col_pins_str} }}\n\n')
                
                vid = config.get('vid', '0x1209').strip() or '0x1209'
                pid = config.get('pid', '0xb803').strip() or '0xb803'
                f.write(f'#define CUSTOM_VID {vid}\n')
                f.write(f'#define CUSTOM_PID {pid}\n\n')
                
                # Split Options
                split = config.get('split', {})
                if split.get('enabled'):
                    f.write('#define CUSTOM_SPLIT_ENABLE 1\n')
                    handedness_pin = clean_pin(split.get('handedness_pin', 'PC3'))
                    f.write(f'#define CUSTOM_HANDEDNESS_PIN {handedness_pin}\n')
                    combine_mode = split.get('combine_mode', 'right_to_left_cols')
                    if combine_mode == 'right_to_left_cols':
                        f.write('#define CUSTOM_SPLIT_COMBINE_COLS 1\n')
                    else:
                        f.write('#define CUSTOM_SPLIT_COMBINE_ROWS 1\n')
                    f.write('\n')
                
                name = config.get('name', 'UIAPduino_VIA').strip() or 'UIAPduino_VIA'
                f.write(f'#define STR_MANUFACTURER u"UIAPduino"\n')
                f.write(f'#define STR_PRODUCT u"{name}"\n')
                
                f.write('\n#endif\n')
                
            # Run make clean & make
            # Using -C to ensure it runs inside firmware folder correctly
            subprocess.run(['make', '-C', fw_dir, 'clean'], check=True, capture_output=True, text=True)
            # Build main.bin specifically to avoid triggering `cv_flash` targets in the default `all` target
            build_res = subprocess.run(['make', '-C', fw_dir, 'main.bin'], check=True, capture_output=True, text=True)
            
            # Read binary
            bin_path = os.path.join(fw_dir, 'main.bin')
            if os.path.exists(bin_path):
                with open(bin_path, 'rb') as f:
                    bin_data = f.read()
                    
                self.send_response(200)
                self.send_header('Content-Type', 'application/octet-stream')
                self.send_header('Content-Disposition', 'attachment; filename="main.bin"')
                self.send_header('Content-Length', str(len(bin_data)))
                self.end_headers()
                self.wfile.write(bin_data)
            else:
                self.send_error(500, "Build completed but main.bin not found.")
                
        except subprocess.CalledProcessError as e:
            err_msg = f"Build failed!\nStdout: {e.stdout}\nStderr: {e.stderr}"
            print(err_msg)
            self.send_error(500, err_msg)
        except Exception as e:
            self.send_error(500, str(e))

if __name__ == "__main__":
    with socketserver.TCPServer(("", PORT), Handler) as httpd:
        print("======== UIAPduino Local Build Server ========")
        print(f"Serving at http://localhost:{PORT}/web/")
        print("Please access the above URL to use the Web Configurator.")
        print("Press Ctrl+C to stop the server.")
        print("==============================================")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nShutting down server...")
