import http.server
import socketserver
import json
import subprocess
import os

PORT = 8000
DIRECTORY = os.path.dirname(os.path.abspath(__file__))


def logical_matrix_size(config):
    """ファームウェアの matrix.h と同じ規則で論理マトリクスのサイズを求める。

    Split 有効時は結合方向に応じて行数または列数が2倍になり、
    VIA/Remap から見えるマトリクスはこの論理サイズになります。
    """
    wiring = config.get('wiring', 'matrix')
    if wiring == 'direct':
        rows = 1
        cols = len(config.get('col_pins', [])) or 1
    else:
        rows = int(config.get('rows', 4))
        cols = int(config.get('cols', 6))

    split = config.get('split', {})
    if split.get('enabled'):
        if split.get('combine_mode', 'right_to_left_cols') == 'right_to_left_cols':
            cols *= 2
        else:
            rows *= 2

    return rows, cols


def normalize_usb_id(value, fallback):
    """Remap のスキーマ (^0x[0-9a-zA-Z]{1,4}$) に合う形へ整える。"""
    text = (value or '').strip() or fallback
    if not text.lower().startswith('0x'):
        text = '0x' + text
    return '0x' + text[2:].lower().lstrip('0').rjust(4, '0')[-4:]


def generate_remap_definition(config):
    """Remap / VIA 用のキーボード定義 JSON を生成する。

    レイアウトはマトリクスそのままの格子として出力します。
    実際のキー配置に合わせたい場合は Web UI の Layout Editor から
    「Remap用 定義JSON」をダウンロードしてください。
    """
    rows, cols = logical_matrix_size(config)

    # VIA/Remap はキーの左上レジェンド "row,col" からマトリクス位置を読み取ります
    keymap = [[f'{r},{c}' for c in range(cols)] for r in range(rows)]

    return {
        'name': (config.get('name') or '').strip() or 'UIAPduino_VIA',
        'vendorId': normalize_usb_id(config.get('vid'), '0x1209'),
        'productId': normalize_usb_id(config.get('pid'), '0xb803'),
        'matrix': {'rows': rows, 'cols': cols},
        'layouts': {'keymap': keymap},
    }


class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=DIRECTORY, **kwargs)

    def do_POST(self):
        if self.path == '/api/build':
            content_length = int(self.headers['Content-Length'])
            post_data = self.rfile.read(content_length)

            try:
                config = json.loads(post_data.decode('utf-8'))
                self.handle_build(config)
            except Exception as e:
                self.send_error(500, f"Error processing build: {str(e)}")
        elif self.path == '/api/remap-definition':
            content_length = int(self.headers['Content-Length'])
            post_data = self.rfile.read(content_length)

            try:
                config = json.loads(post_data.decode('utf-8'))
                self.handle_remap_definition(config)
            except Exception as e:
                self.send_error(500, f"Error generating definition: {str(e)}")
        else:
            self.send_error(404, "Endpoint not found")

    def handle_remap_definition(self, config):
        body = json.dumps(generate_remap_definition(config), indent=2).encode('utf-8')
        self.send_response(200)
        self.send_header('Content-Type', 'application/json; charset=utf-8')
        self.send_header('Content-Disposition', 'attachment; filename="remap_definition.json"')
        self.send_header('Content-Length', str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def handle_build(self, config):
        fw_dir = os.path.join(DIRECTORY, 'firmware')
        config_file = os.path.join(DIRECTORY, 'keyboards', 'uiapduino', 'config.h')
        
        try:
            with open(config_file, 'w', encoding='utf-8') as f:
                f.write('// Auto-generated by build_server.py\n')
                f.write('#ifndef CONFIG_H\n')
                f.write('#define CONFIG_H\n\n')
                f.write(f'#define CUSTOM_MATRIX_ROWS {config.get("rows", 4)}\n')
                f.write(f'#define CUSTOM_MATRIX_COLS {config.get("cols", 6)}\n')
                
                # Check for empty pin
                def clean_pin(p):
                    return p if p else "0"
                
                wiring = config.get('wiring', 'matrix')
                if wiring == 'direct':
                    f.write('#define CUSTOM_DIRECT_PIN_MODE\n\n')
                    direct_pins = config.get('col_pins', [])
                    dp_pins_str = ", ".join([clean_pin(p) for p in direct_pins])
                    f.write(f'#define CUSTOM_COL_PINS {{ {dp_pins_str} }}\n\n')
                else:
                    row_pins = config.get('row_pins', ['PC0', 'PC1', 'PC2', 'PC3'])
                    col_pins = config.get('col_pins', ['PC4', 'PC5', 'PC6', 'PC7', 'PD0', 'PD2'])
                    row_pins_str = ", ".join([clean_pin(p) for p in row_pins])
                    col_pins_str = ", ".join([clean_pin(p) for p in col_pins])
                    f.write(f'#define CUSTOM_ROW_PINS {{ {row_pins_str} }}\n')
                    f.write(f'#define CUSTOM_COL_PINS {{ {col_pins_str} }}\n\n')
                
                vid = config.get('vid', '0x1209').strip() or '0x1209'
                pid = config.get('pid', '0xb803').strip() or '0xb803'
                f.write(f'#define CUSTOM_VID {vid}\n')
                f.write(f'#define CUSTOM_PID {pid}\n\n')
                
                # Split Options
                split = config.get('split', {})
                if split.get('enabled'):
                    f.write('#define CUSTOM_SPLIT_ENABLE 1\n')
                    handedness_pin = clean_pin(split.get('handedness_pin', 'PC3'))
                    f.write(f'#define CUSTOM_HANDEDNESS_PIN {handedness_pin}\n')
                    combine_mode = split.get('combine_mode', 'right_to_left_cols')
                    if combine_mode == 'right_to_left_cols':
                        f.write('#define CUSTOM_SPLIT_COMBINE_COLS 1\n')
                    else:
                        f.write('#define CUSTOM_SPLIT_COMBINE_ROWS 1\n')
                f.write('\n')
                
                # RGB Options
                rgb = config.get('rgb', {})
                if rgb.get('enabled'):
                    f.write('#define CUSTOM_RGB_ENABLE 1\n')
                    f.write('#define CUSTOM_RGB_PIN PC6\n')
                    num_leds = int(rgb.get('num_leds', 1))
                    f.write(f'#define CUSTOM_RGB_NUM_LEDS {num_leds}\n')
                    mode = int(rgb.get('mode', 0))
                    f.write(f'#define CUSTOM_RGB_MODE {mode}\n')
                f.write('\n')
                
                name = config.get('name', 'UIAPduino_VIA').strip() or 'UIAPduino_VIA'
                f.write(f'#define STR_MANUFACTURER u"UIAPduino"\n')
                f.write(f'#define STR_PRODUCT u"{name}"\n')
                
                f.write('\n#endif\n')

            # Remap / VIA 用のキーボード定義 JSON を config.h と同時に更新する
            definition_file = os.path.join(DIRECTORY, 'keyboards', 'uiapduino', 'uiapduino.remap.json')
            with open(definition_file, 'w', encoding='utf-8') as f:
                json.dump(generate_remap_definition(config), f, indent=2)
                f.write('\n')

            # Run make clean & make
            # Using -C to ensure it runs inside firmware folder correctly
            subprocess.run(['make', '-C', fw_dir, 'KEYBOARD=uiapduino', 'clean'], check=True, capture_output=True, text=True)
            # Build main.bin specifically to avoid triggering `cv_flash` targets in the default `all` target
            build_res = subprocess.run(['make', '-C', fw_dir, 'KEYBOARD=uiapduino', 'main.bin'], check=True, capture_output=True, text=True)
            
            # Read binary
            bin_path = os.path.join(fw_dir, 'main.bin')
            if os.path.exists(bin_path):
                with open(bin_path, 'rb') as f:
                    bin_data = f.read()
                    
                self.send_response(200)
                self.send_header('Content-Type', 'application/octet-stream')
                self.send_header('Content-Disposition', 'attachment; filename="main.bin"')
                self.send_header('Content-Length', str(len(bin_data)))
                self.end_headers()
                self.wfile.write(bin_data)
            else:
                self.send_error(500, "Build completed but main.bin not found.")
                
        except subprocess.CalledProcessError as e:
            err_msg = f"Build failed!\nStdout: {e.stdout}\nStderr: {e.stderr}"
            print(err_msg)
            self.send_error(500, err_msg)
        except Exception as e:
            self.send_error(500, str(e))

if __name__ == "__main__":
    with socketserver.TCPServer(("", PORT), Handler) as httpd:
        print("======== UIAPduino Local Build Server ========")
        print(f"Serving at http://localhost:{PORT}/web/")
        print("Please access the above URL to use the Web Configurator.")
        print("Press Ctrl+C to stop the server.")
        print("==============================================")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nShutting down server...")
