// Auto-generated by build_server.py
#ifndef CONFIG_H
#define CONFIG_H

#define CUSTOM_MATRIX_ROWS 1
#define CUSTOM_MATRIX_COLS 3
#define CUSTOM_DIRECT_PIN_MODE

#define CUSTOM_COL_PINS { PD0, PD1, PD2 }

#define CUSTOM_VID 0x1209
#define CUSTOM_PID 0xb803



#define STR_MANUFACTURER u"UIAPduino"
#define STR_PRODUCT u"test"

#endif
