// Auto-generated by build_server.py
#ifndef CUSTOM_CONFIG_H
#define CUSTOM_CONFIG_H

#define CUSTOM_MATRIX_ROWS 4
#define CUSTOM_MATRIX_COLS 12
#define CUSTOM_ROW_PINS { PC0, PC1, PC2, PC3 }
#define CUSTOM_COL_PINS { PC4, PC5, PC6, PC7, PD0, PD1, PC4, PC5, PC6, PC7, PD0, PD1 }
#define CUSTOM_VID 0x1209
#define CUSTOM_PID 0xb803
#define STR_MANUFACTURER u"UIAPduino"
#define STR_PRODUCT u"UIAPduino_VIA"

#endif
