// Auto-generated by build_server.py
#ifndef CUSTOM_CONFIG_H
#define CUSTOM_CONFIG_H

#define CUSTOM_MATRIX_ROWS 1
#define CUSTOM_MATRIX_COLS 1
#define CUSTOM_ROW_PINS {  }
#define CUSTOM_COL_PINS { PA1 }
#define CUSTOM_VID 0x1209
#define CUSTOM_PID 0xb803
#define STR_MANUFACTURER u"UIAPduino"
#define STR_PRODUCT u"UIAPduino_VIA"

#endif
